sonar.projectKey=airport-service
sonar.projectName=Airport Microservice
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/tests/**,**/__pycache__/**
